// This file will be generated by AWS Amplify CLI
// For now, using placeholder values
const awsconfig = {
  aws_project_region: 'us-east-1',
  aws_cognito_identity_pool_id: 'us-east-1:XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_XXXXXXXXX',
  aws_user_pools_web_client_id: 'XXXXXXXXXXXXXXXXXXXXXXXXXX',
  oauth: {},
  aws_cognito_username_attributes: ['username'],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ['name'],
  aws_cognito_mfa_configuration: 'OFF',
  aws_cognito_mfa_types: ['SMS'],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: []
  },
  aws_cognito_verification_mechanisms: ['username'],
  aws_appsync_graphqlEndpoint: 'https://XXXXXXXXXXXXXXXXXXXXXXXXXX.appsync-api.us-east-1.amazonaws.com/graphql',
  aws_appsync_region: 'us-east-1',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
  API: {
    endpoints: [
      {
        name: 'membershipAPI',
        endpoint: 'https://XXXXXXXXXX.execute-api.us-east-1.amazonaws.com/prod',
        region: 'us-east-1'
      }
    ]
  }
};

export default awsconfig;